### ISSUE TITLE
不知道是什么原因chrome无法加载该扩展

### ISSUE THREAD

**Issue by ghost** [L3au/Prism-Pretty#5]
chrome最新版本49.0.2623.108 m

不知道是我设置了什么的原因，扩展无法加载了，什么网站的文件都不行
# 

经测试发现。如果开启了chrome的

> 实验性 JavaScript Mac, Windows, Linux, Chrome OS, Android
> 允许网页使用实验性 JavaScript 功能。 #enable-javascript-harmony

将会导致扩展失效

**Comment by L3au** [comment]
Mac 下  Chrome Dev 版本开启了这个正常的。不知道是不是 #6 这个问题，如果是的话，更新扩展后应该能解决。
