### ISSUE TITLE
Chrome浏览器57版移除编码选项后，含有中文的文件出现乱码

### ISSUE THREAD

**Issue by Attax** [L3au/Prism-Pretty#8]
Chrome浏览器57版移除编码选项后，含有中文的js，css UTF8编码文件会被自动识别为GBK编码，导致Prism-Pretty美化后的也是乱码。为了解决编码问题，同时安装了Chrome扩展“Charset”,该扩展在Prism-Pretty工作的情况下，无法切换编码，禁用Prism-Pretty后重启，可以切换编码，很遗憾无法再使用Prism-Pretty功能。

**Comment by L3au** [comment]
最近刚注意到，实在抱歉。

我看看怎么修复

**Comment by L3au** [comment]
@Attax 已修复，欢迎更新

**Comment by Attax** [comment]
@L3au 非常感谢，这个插件真的非常好用，有方法给你发个红包或表示下赞助吗，顺便问下，更改编码的原理或者方式是啥？
